// Every agent host must expose the same tool surface. A host that drifts, or a
// host that is missing entirely, fails here rather than at install time.
//
// The manifests themselves are generated by scripts/generate-agent-plugins.mjs;
// `pnpm validate:plugins` runs that generator in --check mode first, so this file
// asserts the *shape* the generator is required to produce.

import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const root = resolve(import.meta.dirname, "..");
const { PUBLIC_AGENT_TOOL_NAMES } = await import(
  pathToFileURL(resolve(root, "packages/contracts/dist/agent-tools.js")).href
);
const expectedTools = [...PUBLIC_AGENT_TOOL_NAMES];
assert.equal(
  expectedTools.length,
  6,
  "the public surface is exactly six tools",
);

const readJson = async (relative) =>
  JSON.parse(await readFile(resolve(root, relative), "utf8"));

// --- Codex -----------------------------------------------------------------
const codex = await readJson(
  "plugins/codex/agentintel/.codex-plugin/plugin.json",
);
assert.equal(codex.name, "agentintel");
assert.equal(codex.license, "Apache-2.0");
assert.equal(codex.skills, "./skills/");
const codexMcp = await readJson("plugins/codex/agentintel/.mcp.json");
assert.ok(
  codexMcp.mcpServers?.agentintel,
  "Codex bundle must register its bundled MCP bridge",
);

// --- Claude Code -----------------------------------------------------------
const claude = await readJson(
  "plugins/claude/agentintel/.claude-plugin/plugin.json",
);
assert.equal(claude.name, "agentintel");
assert.equal(claude.license, "Apache-2.0");
assert.equal(claude.skills, "./skills/");
assert.equal(claude.commands, "./commands/");
assert.equal(claude.mcpServers, "./.mcp.json");

const marketplace = await readJson(".claude-plugin/marketplace.json");
assert.equal(marketplace.plugins.length, 1);
assert.equal(marketplace.plugins[0].source, "./plugins/claude/agentintel");
assert.equal(marketplace.plugins[0].license, "Apache-2.0");

// Each generated slash command must reference a tool that actually exists.
const commandsDir = resolve(root, "plugins/claude/agentintel/commands");
const commandFiles = (await readdir(commandsDir)).filter((name) =>
  name.endsWith(".md"),
);
assert.ok(commandFiles.length >= 4, "expected a command per public workflow");
const referenced = new Set();
for (const file of commandFiles) {
  const body = await readFile(resolve(commandsDir, file), "utf8");
  assert.match(body, /^---\ndescription: .+\n---\n/u);
  for (const [, name] of body.matchAll(/`(agentintel_[a-z_]+)`/gu)) {
    assert.ok(
      expectedTools.includes(name),
      `${file} references unknown tool ${name}`,
    );
    referenced.add(name);
  }
}
// run_get is reached from the start-shaped commands rather than its own command.
for (const name of expectedTools) {
  if (name === "agentintel_run_get") continue;
  assert.ok(referenced.has(name), `no slash command reaches ${name}`);
}

// --- OpenClaw --------------------------------------------------------------
const openclaw = await readJson("adapters/openclaw/openclaw.plugin.json");
assert.ok(openclaw.name, "OpenClaw manifest must declare a name");

// --- Shared skill source ---------------------------------------------------
const sharedSkill = await readFile(
  resolve(root, "plugins/shared/skills/intelligence-researcher/SKILL.md"),
  "utf8",
);
for (const host of ["plugins/claude/agentintel", "plugins/codex/agentintel"]) {
  const copy = await readFile(
    resolve(root, host, "skills/intelligence-researcher/SKILL.md"),
    "utf8",
  );
  assert.equal(
    copy,
    sharedSkill,
    `${host} skill copy drifted from the shared source`,
  );
}
for (const toolName of expectedTools) {
  assert.ok(
    sharedSkill.includes(`\`${toolName}\``),
    `shared skill does not document ${toolName}`,
  );
}

// --- Plain MCP editor configs ---------------------------------------------
for (const file of [
  "integrations/cursor.mcp.json",
  "integrations/claude-code.mcp.json",
  "integrations/antigravity.mcp.json",
  "integrations/generic.mcp.json",
]) {
  const config = await readJson(file);
  assert.ok(
    config.mcpServers?.agentintel?.command,
    `${file} has no server command`,
  );
  assert.ok(
    !JSON.stringify(config).includes("/absolute/path/to/"),
    `${file} still contains a placeholder path`,
  );
}
const vscode = await readJson("integrations/vscode.mcp.json");
assert.equal(vscode.servers?.agentintel?.type, "stdio");

assert.ok(
  existsSync(resolve(root, "scripts/render-agent-config.mjs")),
  "the local-path config renderer must remain available",
);

process.stdout.write(
  `Validated Claude Code, Codex, OpenClaw and plain-MCP surfaces against the ${expectedTools.length}-tool registry.\n`,
);
