// Config for short links the operator hosts themselves.
//
// A QR code cannot expire and cannot be re-pointed. The modules encode the
// destination directly, and once printed that is permanent. Every product
// selling "dynamic QR codes" is selling a redirect: the code encodes a short
// URL on *their* domain, and they resolve it — which means they can also stop
// resolving it, meter it, or start charging for it, and every code printed is
// hostage to that.
//
// The honest version of the same capability is to put the redirect on a domain
// the operator already owns. This file emits the configuration to do that. It
// generates no traffic through Marketingovo, requires no account, and keeps
// working if this software is deleted.
//
// It also happens to make the code more scannable: the short URL is a fraction
// of the length of a tagged one, so the symbol needs far fewer modules.

import type { CampaignLinkFinding } from "./types.js";

export type RedirectTarget =
  "cloudflare-worker" | "netlify" | "vercel" | "nginx" | "apache";

export interface RedirectRoute {
  /** The path on the operator's own domain, such as `/s/summer`. */
  path: string;
  /** Where it resolves to: the tagged URL. */
  target: string;
  /** When it should stop resolving, if ever. */
  expiresAt: string | null;
  /** Where an expired code goes instead of failing. */
  fallbackUrl: string | null;
}

export interface RedirectConfig {
  target: RedirectTarget;
  filename: string;
  contents: string;
  /**
   * Whether the platform can enforce an expiry by itself.
   *
   * Static rewrite files cannot: they can hold a date in a comment, but
   * something still has to edit the file when it arrives. Saying so here is
   * the difference between a scheduled expiry and an intention.
   */
  enforcesExpiry: boolean;
  notes: string[];
}

/** A short, stable path from a human label. */
export function shortLinkPath(label: string, prefix = "s"): string {
  const slug = label
    .trim()
    .toLowerCase()
    .normalize("NFKD")
    .replace(/\p{M}/gu, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40)
    .replace(/-+$/g, "");
  return `/${prefix}/${slug || "link"}`;
}

/**
 * 302, never 301.
 *
 * This is the whole point and it is easy to get wrong. A browser caches a
 * permanent redirect indefinitely and will not ask again — so re-pointing a
 * short link later reaches only people who have never scanned it, while
 * everyone who has keeps going to the old destination with no way to clear it
 * remotely. A temporary redirect is what makes the link changeable, which is
 * the only reason to have a redirect at all.
 */
const REDIRECT_STATUS = 302;

const EXPIRY_NOTE =
  "This file cannot expire a link on its own — it has no way to know the date. Either replace it when the campaign ends, or use the Cloudflare Worker version, which checks the expiry on every request.";

const FORWARDING_NOTE =
  "Query parameters a scanner appends are forwarded to the destination unless it already sets the same one, so app tracking added at scan time is not discarded.";

function cloudflareWorker(routes: RedirectRoute[]): string {
  const table = routes
    .map((route) => {
      const expiry = route.expiresAt ? JSON.stringify(route.expiresAt) : "null";
      const fallback = route.fallbackUrl
        ? JSON.stringify(route.fallbackUrl)
        : "null";
      return `  ${JSON.stringify(route.path)}: {\n    target: ${JSON.stringify(route.target)},\n    expiresAt: ${expiry},\n    fallback: ${fallback},\n  },`;
    })
    .join("\n");

  return `// Campaign short links. Generated by Marketingovo.
//
// Deploy to a domain you own. Nothing here calls back to Marketingovo, and
// these links keep resolving whether or not that software is still installed.

const ROUTES = {
${table}
};

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const path = url.pathname.replace(/\\/+$/, "") || "/";
    const route = ROUTES[path];
    if (!route) {
      return new Response("Not found", { status: 404 });
    }

    if (route.expiresAt && Date.now() > Date.parse(route.expiresAt)) {
      // 410 rather than 404: the code was valid and is finished, which is
      // what someone holding an old leaflet needs to be told.
      return route.fallback
        ? Response.redirect(route.fallback, ${REDIRECT_STATUS})
        : new Response("This campaign has ended.", { status: 410 });
    }

    const destination = new URL(route.target);
    for (const [key, value] of url.searchParams) {
      if (!destination.searchParams.has(key)) {
        destination.searchParams.set(key, value);
      }
    }

    // ${REDIRECT_STATUS}, deliberately. A permanent redirect is cached by the
    // browser forever, so re-pointing this link later would reach only people
    // who had never scanned it before.
    return Response.redirect(destination.toString(), ${REDIRECT_STATUS});
  },
};
`;
}

function netlify(routes: RedirectRoute[]): string {
  const lines = routes.map((route) => {
    const expiry = route.expiresAt
      ? `\n# Ends ${route.expiresAt}. Replace this line on that date; Netlify cannot do it for you.`
      : "";
    return `${expiry}\n${route.path}  ${route.target}  ${REDIRECT_STATUS}`;
  });
  return `# Campaign short links. Generated by Marketingovo.
# ${REDIRECT_STATUS} rather than 301: a permanent redirect is cached by the
# browser indefinitely, which would make these links impossible to re-point.
${lines.join("\n")}
`;
}

function vercel(routes: RedirectRoute[]): string {
  return `${JSON.stringify(
    {
      redirects: routes.map((route) => ({
        source: route.path,
        destination: route.target,
        // Not permanent, so the link stays re-pointable.
        permanent: false,
      })),
    },
    null,
    2,
  )}\n`;
}

function nginx(routes: RedirectRoute[]): string {
  const blocks = routes.map((route) => {
    const expiry = route.expiresAt
      ? `\n# Ends ${route.expiresAt}. Remove this block on that date.`
      : "";
    return `${expiry}\nlocation = ${route.path} {\n  return ${REDIRECT_STATUS} "${route.target}";\n}`;
  });
  return `# Campaign short links. Generated by Marketingovo.
# Place inside the relevant server block.
# ${REDIRECT_STATUS} keeps these links re-pointable; 301 would be cached by
# browsers permanently.
${blocks.join("\n")}
`;
}

function apache(routes: RedirectRoute[]): string {
  const rules = routes.map((route) => {
    const expiry = route.expiresAt
      ? `\n# Ends ${route.expiresAt}. Remove this rule on that date.`
      : "";
    const pattern = route.path
      .replace(/^\//, "")
      .replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    return `${expiry}\nRewriteRule ^${pattern}/?$ ${route.target} [R=${REDIRECT_STATUS},L,QSA]`;
  });
  return `# Campaign short links. Generated by Marketingovo.
RewriteEngine On
# QSA forwards any query the scanner appended; R=${REDIRECT_STATUS} keeps the
# link re-pointable, where 301 would be cached by browsers permanently.
${rules.join("\n")}
`;
}

const GENERATORS: Record<
  RedirectTarget,
  {
    filename: string;
    enforcesExpiry: boolean;
    render: (routes: RedirectRoute[]) => string;
  }
> = {
  "cloudflare-worker": {
    filename: "worker.js",
    enforcesExpiry: true,
    render: cloudflareWorker,
  },
  netlify: { filename: "_redirects", enforcesExpiry: false, render: netlify },
  vercel: { filename: "vercel.json", enforcesExpiry: false, render: vercel },
  nginx: {
    filename: "campaign-links.conf",
    enforcesExpiry: false,
    render: nginx,
  },
  apache: { filename: ".htaccess", enforcesExpiry: false, render: apache },
};

export function renderRedirectConfig(
  target: RedirectTarget,
  routes: RedirectRoute[],
): RedirectConfig {
  const generator = GENERATORS[target];
  const wantsExpiry = routes.some((route) => route.expiresAt !== null);
  const notes = [FORWARDING_NOTE];
  if (wantsExpiry && !generator.enforcesExpiry) notes.unshift(EXPIRY_NOTE);
  return {
    target,
    filename: generator.filename,
    contents: generator.render(routes),
    enforcesExpiry: generator.enforcesExpiry,
    notes,
  };
}

/**
 * What is worth saying about a short link before it is printed.
 *
 * The expiry warning is the one that matters: an expiry set on a platform that
 * cannot enforce it is not an expiry, and the difference only surfaces on the
 * day the campaign was supposed to end.
 */
export function adviseRedirect(input: {
  target: RedirectTarget;
  routes: RedirectRoute[];
  /** The host the short path will live on, if known. */
  shortHost: string | null;
}): CampaignLinkFinding[] {
  const findings: CampaignLinkFinding[] = [];
  const generator = GENERATORS[input.target];
  const expiring = input.routes.filter((route) => route.expiresAt !== null);

  if (expiring.length > 0 && !generator.enforcesExpiry) {
    findings.push({
      rule: "redirect-expiry-not-enforced",
      severity: "warning",
      field: "expiresAt",
      message: `This configuration is a static rewrite file, so it cannot check a date. The expiry is written into it as a comment, and the link keeps resolving until someone edits the file.`,
      remedy:
        "Use the Cloudflare Worker version, which checks the expiry on every request, or put a reminder against the end date.",
    });
  }

  for (const route of expiring) {
    if (route.fallbackUrl === null) {
      findings.push({
        rule: "redirect-no-fallback",
        severity: "advice",
        field: "fallbackUrl",
        message: `${route.path} expires with nowhere to go, so a scan after the end date reaches an error page. The printed code stays in the world long after the campaign does.`,
        remedy:
          "Point expired scans at the homepage, or at a page explaining the offer has ended.",
      });
    }
  }

  if (input.shortHost !== null) {
    for (const route of input.routes) {
      let host: string | null = null;
      try {
        host = new URL(route.target).hostname;
      } catch {
        host = null;
      }
      if (host !== null && host === input.shortHost) {
        findings.push({
          rule: "redirect-loops",
          severity: "blocking",
          field: "target",
          message: `${route.path} redirects to ${input.shortHost}, the same host serving the redirect. Depending on the path this either loops until the browser gives up or resolves to itself.`,
          remedy:
            "Point the short link at the destination site, not at itself.",
        });
      }
    }
  }

  return findings;
}
